# LOCALHOST CUSTOMERS API

### Get all customers
GET http://localhost:3000/customers
# Returns a JSON array of all customers in the database.

### Get customer by id 
GET http://localhost:3000/customers/68cf6a7a30e30108d43e3ab5

### Create a new customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{
    "firstName": "Ben",
    "lastName": "Dammy",
    "email": "damilola.degoke@gmail.com",
    "phone": "+2348012345678",
    "birthday": "1992-11-21",
    "favoriteProduct": "Promax",
    "city": "Lag",
    "country": "Niger"
}

### Update an existing customer
PUT http://localhost:3000/customers/68d0a73c6d6d81cdde8e23b8 HTTP/1.1
content-type: application/json

{ 
    "firstName": "Benjamin",
    "lastName": "Dammy",
    "email": "damilola.degoke@gmail.com",
    "phone": "+2348014444444",
    "birthday": "1992-11-21",
    "favoriteProduct": "Promax",
    "city": "kano",
    "country": "Nigeria" 
}

### Delete a customer
DELETE http://localhost:3000/customers/68d0a73c6d6d81cdde8e23b8


# LOCALHOST STUDENTS API

### Get all students
GET http://localhost:3000/students
# Returns a JSON array of all students in the database.

### Get student by id
GET http://localhost:3000/students/68cf6ac330e30108d43e3ac0

### Create a new student
POST http://localhost:3000/students HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "phone": "+2348012345999",
    "birthday": "2001-05-10",
    "major": "Physics",
    "city": "Abuja",
    "country": "Nigeria",
    "gpa": 3.4
}

### Update an existing student
PUT http://localhost:3000/students/68d0a7a76d6d81cdde8e23b9 HTTP/1.1
content-type: application/json

{ 
    "firstName": "Johnny",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "phone": "+2348012222222",
    "birthday": "2001-05-10",
    "major": "Physics",
    "city": "Lagos",
    "country": "Nigeria",
    "gpa": 3.6
}

### Delete a student
DELETE http://localhost:3000/students/68d0a7a76d6d81cdde8e23b9
